version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./doc-summary-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./doc-summary-frontend:/app
