name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (a Docker CLI plugin to bake, build, and push)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub (optional if you want to push the image)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend  # Change this if your Dockerfile is in a different directory
        file: ./backend/Dockerfile
        push: true  # Set this to true to push to Docker Hub
        tags: ayush04h/summarizer:latest

    # Step 5: Log out from Docker Hub
    - name: Log out from Docker Hub
      run: docker logout
